server:
  port: 9527


spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: spring-cloud-zuul-9527
    prefer-ip-address: true

info:
  app.name: wrx

zuul:
  routes:
    wrxDept.serviceId: spring-cloud-provide-dept
    wrxDept.path: /wrxDept/**
  ignored-services: "*"
  prefix: /wrx

